/* ════════════════════════════════════════════════════════════════
   DLG AUTOPARTES — productos-data.js
   Fuente única de datos de productos.
   - En el navegador: se carga como <script> normal y expone `productos`
     como variable global (la usan script.js y build-product-pages.js).
   - En Node: se exporta vía module.exports para el generador de páginas
     estáticas de producto (build-product-pages.js).
════════════════════════════════════════════════════════════════ */

/* ── BASE DE DATOS ──────────────────────────────────────────── */
const productos = [
   // Varios 
   { marca: 'Varios',nombre: 'Silicona RTV', modelo: ['Motores'], tipo:'Varios', precio: 5.00, precioOriginal: null, imagenes: ['Piezas/Varios/Silicona.webp'], descripcion: 'Silicona RTV de alto rendimiento diseñada para juntas de motores. Resistente a aceites, refrigerantes y temperaturas extremas. Ideal para cárter, tapa de válvulas y bombas de agua.',  oferta: false, disponible: true},
    { marca:'varios',  nombre:'Pulidora', modelo:['varios'], tipo:'herramienta', precio:40.00, precioOriginal:null, imagenes:['Piezas/Varios/Pulidora .webp'], descripcion:'Pulidora eléctrica para diversos trabajos de acabado y mantenimiento.', oferta:false, disponible:true },

  // HYUNDAI
  { marca:'hyundai', nombre:'Filtro de Aceite H100', modelo:['h100'], tipo:'filtro', precio:8.00, precioOriginal:null, imagenes:['Piezas/Hyundai/Filtro de Aceite  H100 (Foto 1).webp','Piezas/Hyundai/Filtro de Aceite  H100 (Foto 2).webp'], descripcion:'Filtro original para Hyundai H100. Máxima protección eliminando impurezas. Compatible con motores diesel y gasolina.', oferta:false, disponible:false },
  { marca:'hyundai', nombre:'Junta Block Amianto', modelo:['h100'], tipo:'repuesto', precio:25.00, precioOriginal:null, imagenes:['Piezas/Hyundai/Junta de Block Hyundai H100 20 USD .webp'], descripcion:'Junta de block de alta calidad para Hyundai H100. Sella perfectamente el block y garantiza máxima durabilidad.', oferta:false, disponible:false },
  // PEUGEOT
  { marca:'peugeot', nombre:'Filtro de Aceite M20', modelo:['Peugeot'], tipo:'filtro', precio:8.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Filtro Aceite M20.webp'], descripcion:'Filtro de aceite M20 compatible con todos los modelos Peugeot. Filtración eficiente que protege el motor.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Camisas + Pistones XUD9', modelo:['xud9'], tipo:'repuesto', precio:450.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Camisas Pistones.webp'], descripcion:'Kit completo de camisas y pistones para motores Peugeot. Conjunto de alta precisión para máximo rendimiento.', oferta:true, disponible:true },
  { marca:'peugeot', nombre:'Kit Motor DW8', modelo:['dw8'], tipo:'repuesto', precio:350.00, precioOriginal:450.00, imagenes:['Piezas/Peugeot/Piston aros pasador Camisas DW8.webp'], descripcion:'Oferta especial: Kit de pistones, aros, pasadores y camisas para DW8. Máxima compatibilidad y ahorro.', oferta:true, disponible:true },
  { marca:'peugeot', nombre:'Junta Block Metal', modelo:['dw8','xud9','xud9turbo'], tipo:'repuesto', precio:35.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Junta de Block Metal DVV8 XUD9.webp'], descripcion:'Junta de block metal para motores DW8 y XUD9. Altamente resistente a presiones y temperaturas.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Kit Clutch TUD5', modelo:['tud5'], tipo:'repuesto', precio:130.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Kit Clutch TUD5.webp'], descripcion:'Kit completo de embrague para motor TUD5. Incluye disco, plato y rodamiento de empuje.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Kit de Retenes', modelo:['Peugeot'], tipo:'repuesto', precio:35.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Kit de Retenes (peugeot).webp'], descripcion:'Kit completo de retenes para motores Peugeot. Evita fugas de aceite y protege los componentes internos.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Kit Distribución DW8', modelo:['dw8'], tipo:'correa', precio:95.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Kit Distribucion DVV8.webp'], descripcion:'Kit de distribución completo para motor DW8. Incluye correa y tensores de alta durabilidad.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Kit Distribución TUD5', modelo:['tud5'], tipo:'correa', precio:95.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Kit Distribucion TUD5.webp'], descripcion:'Kit de distribución completo para motor TUD5. Garantiza la sincronización perfecta de tu motor.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Kit Distribución XUD', modelo:['xud7','xud9'], tipo:'correa', precio:95.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Kit Distribucion XUD9 XUD7.webp'], descripcion:'Kit de distribución para motores XUD7 y XUD9. Componentes reforzados para larga vida útil.', oferta:false, disponible:true },
  { marca:'Aceite', nombre:'Líquido Freno 1L', modelo:['Mannol'], tipo:'Liquido', precio:10.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Liquido Freno (1 litro).webp'], descripcion:'Líquido de freno de 1 litro, especificación DOT 4. Alta resistencia térmica para frenado seguro.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Metales Biela y Bancada', modelo:['tud5','xud9','dw8'], tipo:'repuesto', precio:80.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Metales de Biela y Bancada TUD5 XUD9 XUD9turbo DVV8 TU5JP4(301).webp'], descripcion:'Metales de biela y bancada para motores TUD5, XUD9 y DW8. Precisión y resistencia garantizadas.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Metales Biela y Bancada', modelo:['xud9turbo','tu5jp4'], tipo:'repuesto', precio:90.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Metales de Biela y Bancada TUD5 XUD9 XUD9turbo DVV8 TU5JP4(301).webp'], descripcion:'Metales de biela y bancada específicos para motores XUD9 Turbo y TU5JP4 (301).', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Motor de Arranque TUD5', modelo:['tud5','tu5jp4'], tipo:'repuesto', precio:130.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Motor Aranque TUD5 TU5JP4(301).webp'], descripcion:'Motor de arranque compatible con motores TUD5 y TU5JP4. Alta fiabilidad de encendido.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Motor de Arranque XUD/DW', modelo:['xud7','xud9','dw8'], tipo:'repuesto', precio:150.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Motor Aranque XUD9 DVV8 XUD7.webp'], descripcion:'Motor de arranque reforzado para motores XUD7, XUD9 y DW8.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Kit Pistones Aros Pasador', modelo:['tud5'], tipo:'repuesto', precio:290.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Piston Aros Pasador TUD5.webp'], descripcion:'Kit completo de pistones, aros y pasadores de alta precisión para reconstrucción de motor.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Kit Pistones Aros Pasador', modelo:['xud9','xud7','dw8'], tipo:'repuesto', precio:290.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Kit Pistones Aros Pasador XUD9 XUD7 DW8.webp'], descripcion:'Kit completo de pistones, aros y pasadores de alta precisión para reconstrucción de motor.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Pulmón Presión Aceite', modelo:['Peugeot'], tipo:'repuesto', precio:15.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Pulmon presion Aceite Peugeot.webp'], descripcion:'Sensor de presión de aceite para motores Peugeot. Monitoreo preciso del sistema de lubricación.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Radiador 301', modelo:['301'], tipo:'repuesto', precio:130.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Radiador 301.webp'], descripcion:'Radiador refrigerante para motor Peugeot 301. Máxima eficiencia de enfriamiento térmico.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Radiador 106', modelo:['106'], tipo:'repuesto', precio:100.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Radiador 106 .webp'], descripcion:'Radiador refrigerante para motor Peugeot 106. Máxima eficiencia de enfriamiento térmico.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Retenes de Bastón', modelo:['xud9','dw8'], tipo:'repuesto', precio:10.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Retenes de Baston XUD9 DVV8 (foto2).webp'], descripcion:'Retenes de bastón de alta calidad para motores XUD9 y DW8.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Tornillos Block', modelo:['xud9','dw8'], tipo:'repuesto', precio:50.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Tornillos Block XUD9 DVV8.webp'], descripcion:'Set de tornillos de block de alta resistencia para motores XUD9 y DW8.', oferta:false, disponible:true },
  { marca:'Aceite', nombre:'Aceite Caja Automática 1L', modelo:['Castrol'], tipo:'aceite', precio:12.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Aceite Caja Automatica.webp'], descripcion:'Aceite especializado para cajas de cambio automáticas. Presentación de 1 Litro.', oferta:false, disponible:false },
  { marca:'Aceite', nombre:'Aceite Caja Mecánica 4L', modelo:['Mannol'], tipo:'aceite', precio:25.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Aceite Caja Mecanica (4 litros).webp'], descripcion:'Lubricante para transmisiones manuales. Formato de 4 litros para mantenimiento completo.', oferta:false, disponible:true },
  { marca:'Aceite', nombre:'Aceite Motor 10W-40 1L', modelo:['Fanfaro'], tipo:'aceite', precio:9.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Aceite Motor 10W-40 (1 litro).webp'], descripcion:'Aceite motor semisintético 10W-40. Botella de 1 litro para relleno o servicio.', oferta:false, disponible:true },
  { marca:'Aceite', nombre:'Aceite Motor 15W-40 5L', modelo:['Fanfaro'], tipo:'aceite', precio:20.00, precioOriginal:25.00, imagenes:['Piezas/Peugeot/Aceite Motor 15W-40 (5 litros).webp'], descripcion:'Aceite mineral 15W-40 en formato ahorro de 5 litros. Excelente protección al motor.', oferta:false, disponible:false },
  { marca:'Aceite', nombre:'Aceite Motor 20W-50 1L', modelo:['Fanfaro'], tipo:'aceite', precio:9.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Aceite Motor 20W-50 (1 litro).webp'], descripcion:'Aceite motor 20W-50 para climas cálidos o motores con alto kilometraje. 1 Litro.', oferta:false, disponible:true },
  { marca:'Aceite', nombre:'Aceite Motor 20W-50 5L', modelo:['Fanfaro'], tipo:'aceite', precio:20.00, precioOriginal:25.00, imagenes:['Piezas/Peugeot/Aceite Motor 20W-50 (5 litros).webp'], descripcion:'Aceite motor 20W-50 de alto rendimiento en formato familiar de 5 litros.', oferta:true, disponible:true },
  { marca:'peugeot', nombre:'Arandelas Traslado TUD5', modelo:['tud5'], tipo:'repuesto', precio:20.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Arandelas de Traslado TUD5 XUD9 DVV8 XUD9turbo (foto1).webp'], descripcion:'Arandelas de traslado para motor TUD5. Fabricadas con materiales de alta resistencia.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Arandelas Traslado XUD9/DW8', modelo:['xud9','xud9turbo','dw8'], tipo:'repuesto', precio:25.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Arandelas de Traslado TUD5 XUD9 DVV8 XUD9turbo (foto1).webp'], descripcion:'Arandelas de traslado para motores XUD9, XUD9 Turbo y DW8.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Árbol de Levas', modelo:['xud7','xud9','dw8'], tipo:'repuesto', precio:120.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Arbol Levas XUD7 XUD9 DVV8.webp'], descripcion:'Árbol de levas para motores XUD7, XUD9 y DW8. Acero forjado de alta resistencia.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Bobina Encendida 301', modelo:['301'], tipo:'repuesto', precio:95.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Bobina Encendida 301.webp'], descripcion:'Bobina de encendido de alta tensión para motor 301. Chispa constante y eficiente.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Aros de Pistón', modelo:['tud5','xud9','dw8'], tipo:'repuesto', precio:80.00, precioOriginal:85.00, imagenes:['Piezas/Peugeot/Aros de Piston  TUD5 XUD9 XUD9Turbo DVV8 TU5JP4(301).webp'], descripcion:'Aros de pistón de alta calidad. Garantizan sellado perfecto y máxima compresión.', oferta:true, disponible:true },
  { marca:'peugeot', nombre:'Aros de Pistón TU5JP4', modelo:['tu5jp4'], tipo:'repuesto', precio:100.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Aros de Piston  TUD5 XUD9 XUD9Turbo DVV8 TU5JP4(301).webp'], descripcion:'Aros de pistón específicos para motor TU5JP4. Diseño optimizado para inyección.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Aros de Pistón Turbo', modelo:['xud9turbo'], tipo:'repuesto', precio:95.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Aros de Piston  TUD5 XUD9 XUD9Turbo DVV8 TU5JP4(301).webp'], descripcion:'Aros de pistón para motor XUD9 Turbo. Diseñados para soportar presiones elevadas.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Bomba de Agua TU3', modelo:['t1','tu3'], tipo:'repuesto', precio:35.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Bomba Agua T1 TU3.webp'], descripcion:'Bomba de agua para motores T1 y TU3. Flujo optimizado para evitar calentamiento.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Bomba de Agua TUD5/301', modelo:['tud5','tu5jp4'], tipo:'repuesto', precio:40.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Bomba Agua TUD5 TUD5JP4(301).webp'], descripcion:'Bomba de agua de alta durabilidad para motores TUD5 y TU5JP4.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Bomba de Agua XUD9', modelo:['xud9'], tipo:'repuesto', precio:40.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Bomba Agua XUD9 40 usd.webp'], descripcion:'Bomba de agua para motor XUD9. Alta durabilidad y rendimiento óptimo.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Brazos Cremallera 301', modelo:['301'], tipo:'repuesto', precio:40.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Brazos Cremallera 301.webp'], descripcion:'Brazos de cremallera de dirección para Peugeot 301. Precisión total en el manejo.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Brazos Cremallera 405', modelo:['405'], tipo:'repuesto', precio:40.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Brazos Cremallera 405.webp'], descripcion:'Brazos de cremallera de dirección específicos para Peugeot 405.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Bujías Precalentamiento', modelo:['xud9'], tipo:'repuesto', precio:35.00, precioOriginal:40.00, imagenes:['Piezas/Peugeot/Bujias de Precalentamiento XUD9.webp'], descripcion:'Set de 4 bujías para motor diesel XUD9. .', oferta:true, disponible:true },
  {marca:'peugeot', nombre:'Bujía Precalentamiento ', modelo:['xud9'], tipo:'repuesto', precio:10.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Bujia (sola).webp'], descripcion:'Bujía para motor XUD9. Resistencia mejorada para altas temperaturas.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Camisas Cilindro TUD5', modelo:['tud5'], tipo:'repuesto', precio:180.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Camisas TUD5 XUD9 DVV8.webp'], descripcion:'Camisas de cilindro para motor TUD5. Resistencia extrema al desgaste y calor.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Camisas XUD9 / DW8', modelo:['xud9','dw8'], tipo:'repuesto', precio:160.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Camisas TUD5 XUD9 DW8.webp'], descripcion:'Camisas de cilindro para motores XUD9 y DW8. Material de primera calidad OEM.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Cubo de Rueda', modelo:['205','206','207','308','306','307','309','405','406','partner'], tipo:'repuesto', precio:80.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Cubo de Rueda (Peugeo citroent) (foto1) 205 206 207 308 306 307 309 405 406 Partner.webp'], descripcion:'Cubo de rueda compatible con amplia gama de modelos Peugeot y Citroën.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Dampers DW8', modelo:['dw8'], tipo:'repuesto', precio:70.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Dampers DVV8.webp'], descripcion:'Polea Damper para motor DW8. Absorbe vibraciones críticas del cigüeñal.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Electroventilador 301', modelo:['301'], tipo:'repuesto', precio:100.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Electroventilador (peugeot) 301 Citroen.webp'], descripcion:'Electroventilador completo para motor 301 y Citroën compatibles.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Junta Block Amianto', modelo:['tud5'], tipo:'repuesto', precio:25.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Junta Block Amianto TUD5.webp'], descripcion:'Junta de culata/block de amianto clásica para motor TUD5.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Amortiguadores (Par)', modelo:['301','405','205'], tipo:'repuesto', precio:160.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Amortiguadores Delanteros 301 405 205GTI.webp'], descripcion:'Kit de dos amortiguadores delanteros. Máxima estabilidad para varios modelos.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Disco Clutch DW8/XUD9', modelo:['dw8','xud9'], tipo:'repuesto', precio:70.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Disco Clutch DW8 XUD9 (FOTO1).webp'], descripcion:'Disco de embrague reforzado para motores diesel DW8 y XUD9.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Kit Juntas 301', modelo:['301'], tipo:'repuesto', precio:120.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Kit Juntas 301.webp'], descripcion:'Kit completo de empaquetaduras para motor 301. Calidad superior OEM.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Kit Juntas XUD9', modelo:['xud9'], tipo:'repuesto', precio:105.00, precioOriginal:null, imagenes:['Piezas/Peugeot/kit junta xud9 .webp'], descripcion:'Kit completo de empaquetaduras para motor XUD9. Calidad superior OEM.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Válvula Electrónica', modelo:['Lucas','Bosch'], tipo:'repuesto', precio:35.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Valvula Electronica de Bomba Lucas y Bosch.webp'], descripcion:'Válvula de corte para bombas Lucas y Bosch. Sistemas de inyección Diesel.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Bieleta Suspensión 406', modelo:['406'], tipo:'repuesto', precio:30.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Bieleta Suspension 406.webp'], descripcion:'Bieleta de barra estabilizadora para Peugeot 406. Elimina ruidos en suspensión.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Cable Clutch 306', modelo:['306'], tipo:'repuesto', precio:30.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Cable Clutch 306.webp'], descripcion:'Cable de embrague de reemplazo para Peugeot 306. Movimiento suave y duradero.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Correa 6PK 17.39', modelo:['Peugeot'], tipo:'correa', precio:25.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Correa 6PK 17.39.webp'], descripcion:'Correa poli-V 6PK 17.39 para varios modelos Peugeot. Transmite potencia del motor de manera eficiente.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Correa 5PK775', modelo:['Peugeot'], tipo:'correa', precio:20.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Correa 5PK775.webp'], descripcion:'Correa poli-V 5PK775 de alta calidad. Compatible con varios modelos Peugeot y universal. Resistente al calor y desgaste.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Correa Distribución 136/140/141', modelo:['136','140','141'], tipo:'correa', precio:35.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Correa Distribucion136,140,141(foto1).webp','Piezas/Peugeot/Correa Distribucion136,140,141(foto2).webp'], descripcion:'Correa de distribución para modelos 136, 140 y 141. Garantiza sincronización perfecta.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Dampers TUD5', modelo:['tud5'], tipo:'repuesto', precio:70.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Dampers TUD5.webp'], descripcion:'Polea Damper para motor TUD5. Absorbe vibraciones y protege el cigüeñal.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Dampers XUD9/XUD7', modelo:['xud9','xud7'], tipo:'repuesto', precio:70.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Dampers XUD9 XUD7.webp'], descripcion:'Polea Damper para motores XUD9 y XUD7. Componentes premium de alta durabilidad.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Esféricas 301', modelo:['301'], tipo:'repuesto', precio:50.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Esfericas 301.webp'], descripcion:'Esféricas de suspensión para Peugeot 301. Conexiones robustas y precisas.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Filtro Petroleo TUD5', modelo:['tud5'], tipo:'filtro', precio:15.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Filtro Petroleo TUD5.webp'], descripcion:'Filtro de combustible para motor TUD5. Protección contra impurezas en el sistema.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Guías Válvulas DW8/XUD9', modelo:['dw8','xud9'], tipo:'repuesto', precio:50.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Guias Valvulas DW8 XUD9.webp'], descripcion:'Guías de válvulas para motores DW8 y XUD9. Material de precisión extrema.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Junta Balancines XUD9', modelo:['xud9'], tipo:'repuesto', precio:15.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Junta de Balancines XUD9 (foto1).webp','Piezas/Peugeot/Junta de Balancines XUD9 (foto2).webp'], descripcion:'Junta de balancines para motor XUD9. Evita fugas de aceite en la culata.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Junta Balancines TUD5', modelo:['tud5'], tipo:'repuesto', precio:15.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Junta Balancines TUD5.webp'], descripcion:'Junta de balancines para motor TUD5. Evita fugas de aceite en la culata.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Junta Block Metal TUD5', modelo:['tud5'], tipo:'repuesto', precio:40.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Junta Block Metal TUD5.webp'], descripcion:'Junta de block metal para motor TUD5. Resistencia superior a presión y temperatura.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Junta Block Amianto DW8/XUD9', modelo:['dw8','xud9'], tipo:'repuesto', precio:25.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Junta de Block Amianto DVV8 XUD9.webp'], descripcion:'Junta de block amianto para motores DW8 y XUD9. Sellado de larga duración.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Junta Block Amianto TU3', modelo:['t1','tu3'], tipo:'repuesto', precio:25.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Junta de Block Amianto TU3 25 USD .webp'], descripcion:'Junta de block amianto para motores T1 y TU3. Compatibilidad perfecta garantizada.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Kit Distribución 301', modelo:['301'], tipo:'correa', precio:95.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Kit Distribucion 301.webp'], descripcion:'Kit completo de distribución para motor 301. Incluye correa, tensores y rodillos.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Obturadores TUD5/XUD9/DW8/TU3', modelo:['tud5','xud9','dw8','t1','tu3'], tipo:'repuesto', precio:15.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Obturadores TUD5 XUD9 DW8 TU3.webp'], descripcion:'Obturadores universales para varios motores Peugeot. Cierres hermético seguros.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Parrillas 301', modelo:['301'], tipo:'repuesto', precio:140.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Parrillas 301.webp'], descripcion:'Parrilla/rejilla frontal para Peugeot 301. Acabado cromado y resistente.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Radiador 205', modelo:['205'], tipo:'repuesto', precio:100.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Radiador 205.webp'], descripcion:'Radiador refrigerante para Peugeot 205. Mantiene temperatura óptima del motor.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Rodamiento Delantero Universal', modelo:['Peugeot'], tipo:'repuesto', precio:50.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Rodamiento Delantero Universal CITROEN.webp'], descripcion:'Rodamiento de rueda frontal universal para Peugeot y Citroën. Precisión de giro superior. Medida 72x37x33.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Rodamiento Delantero', modelo:['405'], tipo:'repuesto', precio:60.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Rodamiento 405 .webp'], descripcion:'Rodamiento delantero para modelo 405. Medida 82x42x36. La pareja: 60 USD', disponible: true },
  { marca:'peugeot', nombre:'Tensor Dinámico XUD9', modelo:['xud9'], tipo:'repuesto', precio:40.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Tensor Dinamico XUD9 (FOTO1).webp'], descripcion:'Tensor dinámico para motor XUD9. Mantiene la tensión correcta de la distribución.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Válvulas XUD9/DW8', modelo:['xud9','dw8'], tipo:'repuesto', precio:50.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Valvulas XUD9 DW8 TUD5.webp'], descripcion:'Set de válvulas para motores XUD9, DW8 y TUD5. Calidad OEM premium.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Válvulas TUD5', modelo:['tud5'], tipo:'repuesto', precio:85.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Valvulas XUD9 DW8 TUD5.webp'], descripcion:'Kit de válvulas para motor TUD5. Fabricadas con precisión de fábrica.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Cadena de Bomba de Aceite', modelo:['tud5','dw8'], tipo:'repuesto', precio:20.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Cadena de Bomba de Aceite TUD5 - DW8.jpeg'], descripcion:'Cadena de bomba de aceite para motores TUD5 y DW8. Garantiza la circulación constante de lubricante.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Piñón de Bomba de Aceite', modelo:['tud5'], tipo:'repuesto', precio:15.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Piñon de Bomba de Aceite TUD5.webp'], descripcion:'Piñón para bomba de aceite motor TUD5. Componente esencial para la distribución de lubricante.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Bomba Petróleo', modelo:['tud5','dw8'], tipo:'repuesto', precio:250.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Bomba Petróleo TUD5 DW8.webp'], descripcion:'Bomba de combustible para motores TUD5 y DW8. Suministro constante de carburante de precisión.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Toma Trasera de Agua', modelo:['tud5'], tipo:'repuesto', precio:40.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Toma Trasera de Agua TUD5.webp'], descripcion:'Conexión trasera de agua para sistema de refrigeración motor TUD5. Acceso a líneas traseras.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Tornillos Block', modelo:['tud5'], tipo:'repuesto', precio:60.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Tornillos Block tud5 10 unidades.webp'], descripcion:'Set de 10 tornillos de block para motor TUD5. Resistencia y precisión de fábrica.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Base Piñón Árbol de Levas', modelo:['tud5'], tipo:'repuesto', precio:40.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Base Piñón Arbol de Levas tud5.webp'], descripcion:'Base de soporte para piñón del árbol de levas en motor TUD5. Componente crítico de transmisión.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Árbol de Levas', modelo:['tud5'], tipo:'repuesto', precio:60.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Arbol de levas tud5.webp'], descripcion:'Árbol de levas completo para motor TUD5. Acero forjado de alta resistencia.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Taqué Motor', modelo:['tud5'], tipo:'repuesto', precio:80.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Taqué Motor tud5.webp'], descripcion:'Taqué o compensador automático para motor TUD5. Mantiene tensión correcta en válvulas.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Juego de Inyectores', modelo:['tud5','dw8'], tipo:'repuesto', precio:100.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Juego de Inyectores tud5 dw8.webp'], descripcion:'Set completo de inyectores para motores TUD5 y DW8. Atomización perfecta de combustible.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Depresor TUD5', modelo:['tud5'], tipo:'repuesto', precio:90.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Depresor TUD5.webp'], descripcion:'Depresor de freno para motor TUD5. Sistema de vacío asistido confiable.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Tapa de Balancines', modelo:['tud5'], tipo:'repuesto', precio:60.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Tapa de Balancines TUD5 con los Tornillos y la junta de Balancines.webp'], descripcion:'Tapa de balancines completa para motor TUD5, incluye tornillos y junta. Acceso fácil a los balancines para mantenimiento y reparación.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Juego de Bielas XUD9/DW8', modelo:['xud9', 'dw8'], tipo:'repuesto', precio:150.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Bielas_xud9_dw8.webp'], descripcion:'Juego de 4 bielas de motor para Peugeot XUD9 y DW8. Incluye bujes instalados. Componentes esenciales de alta resistencia que conectan el pistón con el cigüeñal.', oferta:false, disponible:true }, 
  { marca:'peugeot', nombre:'Termostato TUD5', modelo:['tud5'], tipo:'repuesto', precio:15.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Termostato TUD5.webp'], descripcion:'Termostato para motor TUD5, garantiza el control óptimo de la temperatura del refrigerante.', oferta:false, disponible:true },
  { marca:'peugeot', nombre:'Filtro de aire DW8', modelo:['dw8'], tipo:'repuesto', precio:15.00, precioOriginal:null, imagenes:['Piezas/Peugeot/Filtro Aire DW8.webp'], descripcion:'Filtro de aire de alto rendimiento diseñado para motor DW8.', oferta:false, disponible:true }
];

/* ── SLUGS ÚNICOS POR PRODUCTO ──────────────────────────────────
   Necesarios para poder compartir un enlace individual por producto
   (WhatsApp / Facebook / copiar enlace) que apunte a su propia
   página estática con foto, precio y descripción. */
const slugify = str =>
  String(str).toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

productos.forEach((p, i) => {
  p.id   = i;
  p.slug = `${slugify(p.marca)}-${slugify(p.nombre)}-${i}`;
});

/* Exponer en Node (build-product-pages.js) sin romper el navegador */
if (typeof module !== 'undefined' && module.exports) {
  module.exports = productos;
}
